<?xml version="1.0"?>
<!DOCTYPE user_tbl
[   
    <!ELEMENT user_tbl (user+)>
    <!ELEMENT user (user_name, user_address, user_phone_num)>
    <!ELEMENT user_name (#PCDATA)>
    <!ELEMENT user_address (#PCDATA)>
    <!ELEMENT user_phone_num (#PCDATA)>
    <!ATTLIST user id CDATA #REQUIRED>
]>
<user_tbl>
    <user id = "1">
        <user_name>
            홍길동
        </user_name>

        <user_address>
            광진구
        </user_address>
        <user_phone_num>
            01012341234
        </user_phone_num>
    </user>
    <user id = "2">
        <user_name>
            장길동
        </user_name>

        <user_address>
            양천구
        </user_address>
        <user_phone_num>
            01012341235
        </user_phone_num>
    </user>
    <user id = "3">
        <user_name>
            김길동
        </user_name>

        <user_address>
            은평구
        </user_address>
        <user_phone_num>
            01012341236
        </user_phone_num>
    </user>
    <user id = "4">
        <user_name>
            안길동
        </user_name>

        <user_address>
            서대문구
        </user_address>
        <user_phone_num>
            01012343213
        </user_phone_num>
    </user>
    <user id = "5">
        <user_name>
            이길동
        </user_name>

        <user_address>
            송파구
        </user_address>
        <user_phone_num>
            01013213215
        </user_phone_num>
    </user>
    <user id = "6">
        <user_name>
            정길동
        </user_name>

        <user_address>
            중구
        </user_address>
        <user_phone_num>
            01035451234
        </user_phone_num>
    </user>
    <user id = "7">
        <user_name>
            오길동
        </user_name>

        <user_address>
            성북구
        </user_address>
        <user_phone_num>
            01015123802
        </user_phone_num>
    </user>
    <user id = "8">
        <user_name>
            길길동
        </user_name>

        <user_address>
            강남구
        </user_address>
        <user_phone_num>
            01003031257
        </user_phone_num>
    </user>
    <user id = "9">
        <user_name>
            성길동
        </user_name>

        <user_address>
            강동구
        </user_address>
        <user_phone_num>
            01012477123
        </user_phone_num>
    </user>
    <user id = "10">
        <user_name>
            전길동
        </user_name>

        <user_address>
            영등포구
        </user_address>
        <user_phone_num>
            01058123812
        </user_phone_num>
    </user>
</user_tbl>